name: 🚩 Feature Flag 管理票
description: FeatureFlag導入時の運用チケット
title: "[FF] <フラグ名>"
labels: [feature-flags-plan]
body:
  - type: input
    id: flag_name
    attributes:
      label: フラグ名
      description: application.yml に記載するキー名
  - type: textarea
    id: purpose
    attributes:
      label: フラグの目的
      description: なぜこのフラグが必要か／切り戻しの可能性など
  - type: input
    id: removal_date
    attributes:
      label: 除去予定日
      description: 除去する予定日（YYYY-MM-DD）
  - type: textarea
    id: code_links
    attributes:
      label: フラグ適用コード位置（後から追記OK）
      description: 実装完了後にGitHubパーマリンクで記載
  - type: textarea
    id: notes
    attributes:
      label: 備考
      description: その他コメントや関連PR, JIRAなど
