# .github/workflows/check-expired-flags.yml
name: Check Expired FeatureFlags

on:
  schedule:
    - cron: "0 10 * * 1"  # 毎週月曜 10:00 JST（UTC 1:00）
  workflow_dispatch:

permissions: 
  contents: read
  issues: read

jobs:
  check-flags:
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO: ${{ github.repository }}
      ISSUE_LABEL: feature-flag
      GITHUB_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Install dotenv
        run: pip install python-dotenv

      - name: Run expired flag check
        run: python .github/scripts/check_expired_flags.py
