# .github/workflows/check-expired-flags.yml
name: Check Expired FeatureFlags

on:
  schedule: # 毎日 9:00 JST（土日を除く）
    - cron: '0 0 * * 1-5'
  workflow_dispatch:

permissions: 
  contents: write
  issues: write
  pull-requests: write

jobs:
  check-flags:
    runs-on: ubuntu-latest
    environment: ActionsSecret
    env:
      GITHUB_REPO: ${{ github.repository }}

    steps:
      - name: Generate GitHub App Token
        id: generate-github-app-token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.ISSUE_IN_PROJECT_TOOL_APP_ID }} # GitHub AppのID
          private_key: ${{ secrets.ISSUE_IN_PROJECT_TOOL_PRIVATE_KEY }} # GitHub Appの秘密鍵

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Install dotenv
        run: pip install python-dotenv

      - name: Run expired flag check
        env:
          GITHUB_TOKEN: ${{ steps.generate-github-app-token.outputs.token }}
        run: python .github/scripts/check_expired_flags.py
