# .github/workflows/check-expired-flags.yml
name: Check Expired FeatureFlags

on:
  schedule: # 毎日 9:00 JST（土日を除く）
    - cron: '0 0 * * 1-5'
  workflow_dispatch:

permissions: 
  contents: read
  issues: read

jobs:
  check-flags:
    runs-on: ubuntu-latest
    environment: ActionsSecret
    env:
      GITHUB_REPO: ${{ github.repository }}
      ISSUE_LABEL: feature-flag # GitHubでこのラベルを用意しておいてください
      GITHUB_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Install dotenv
        run: pip install python-dotenv

      - name: Run expired flag check
        run: python .github/scripts/check_expired_flags.py
